<?php

if(function_exists("register_field_group"))
{
  register_field_group(array (
    'id' => 'acf_map-fields',
    'title' => 'Map Fields',
    'fields' => array (
      array (
        'key' => 'field_522d51fe96c2a',
        'label' => 'Map Background Colour',
        'name' => 'map_background_color',
        'type' => 'color_picker',
        'required' => 1,
        'default_value' => '#000000',
      ),
      array (
        'key' => 'field_522d520f96c2b',
        'label' => 'Map Background Image',
        'name' => 'map_background',
        'type' => 'image',
        'instructions' => 'This will be the background image for each of the routes. It should be transparent in areas where the background tile is to show through',
        'required' => 1,
        'save_format' => 'object',
        'preview_size' => 'thumbnail',
        'library' => 'all',
      ),
      array (
        'key' => 'field_52314ff77a133',
        'label' => 'Map Labels',
        'name' => 'map_labels',
        'type' => 'repeater',
        'sub_fields' => array (
          array (
            'key' => 'field_5231500c7a134',
            'label' => 'Text',
            'name' => 'text',
            'type' => 'text',
            'column_width' => '',
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'formatting' => 'html',
            'maxlength' => '',
          ),
          array (
            'key' => 'field_523150147a135',
            'label' => 'Position - Percentage from left edge',
            'name' => 'position_x',
            'type' => 'number',
            'column_width' => '',
            'default_value' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '%',
            'min' => '',
            'max' => '',
            'step' => '',
          ),
          array (
            'key' => 'field_523150347a136',
            'label' => 'Position - Percentage from top edge',
            'name' => 'position_y',
            'type' => 'number',
            'column_width' => '',
            'default_value' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '%',
            'min' => '',
            'max' => '',
            'step' => '',
          ),
        ),
        'row_min' => 0,
        'row_limit' => '',
        'layout' => 'table',
        'button_label' => 'Add Label',
      ),
      array (
        'key' => 'field_522d522396c2c',
        'label' => 'Routes',
        'name' => 'routes',
        'type' => 'repeater',
        'required' => 1,
        'sub_fields' => array (
          array (
            'key' => 'field_522d524996c2d',
            'label' => 'Name',
            'name' => 'name',
            'type' => 'text',
            'column_width' => '',
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'formatting' => 'none',
            'maxlength' => '',
          ),
          array (
            'key' => 'field_522d525e96c2e',
            'label' => 'Route Image',
            'name' => 'route_image',
            'type' => 'image',
            'instructions' => 'This will be overlayed on top of the map background image - it should be exactly the same size. The image should have the route over a transparent background.',
            'column_width' => '',
            'save_format' => 'object',
            'preview_size' => 'thumbnail',
            'library' => 'all',
          ),
          array (
            'key' => 'field_522d52ee96c2f',
            'label' => 'Markers',
            'name' => 'markers',
            'type' => 'repeater',
            'instructions' => 'These markers will be shown on the route',
            'column_width' => '',
            'sub_fields' => array (
              array (
                'key' => 'field_522d65480ec83',
                'label' => 'Balloon Text',
                'name' => 'balloon_text',
                'type' => 'wysiwyg',
                'column_width' => '',
                'default_value' => '',
                'toolbar' => 'basic',
                'media_upload' => 'no',
              ),
              array (
                'key' => 'field_522d53b496c32',
                'label' => 'Position - Percentage from left edge',
                'name' => 'position_x',
                'type' => 'number',
                'column_width' => '',
                'default_value' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '%',
                'min' => '',
                'max' => '',
                'step' => '',
              ),
              array (
                'key' => 'field_522d540196c33',
                'label' => 'Position - Percentage from top edge',
                'name' => 'position_y',
                'type' => 'number',
                'column_width' => '',
                'default_value' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '%',
                'min' => '',
                'max' => '',
                'step' => '',
              ),
            ),
            'row_min' => 0,
            'row_limit' => '',
            'layout' => 'table',
            'button_label' => 'Add Marker',
          ),
          array (
            'key' => 'field_522ffce3bec52',
            'label' => 'U-turns',
            'name' => 'u-turns',
            'type' => 'repeater',
            'instructions' => 'U-turn icons will be shown on the route',
            'column_width' => '',
            'sub_fields' => array (
              array (
                'key' => 'field_522ffcf7bec53',
                'label' => 'Text',
                'name' => 'text',
                'type' => 'text',
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
              ),
              array (
                'key' => 'field_522ffd1abec54',
                'label' => 'Position - Percentage from left edge',
                'name' => 'position_x',
                'type' => 'number',
                'column_width' => '',
                'default_value' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '%',
                'min' => '',
                'max' => '',
                'step' => '',
              ),
              array (
                'key' => 'field_522ffd2dbec55',
                'label' => 'Position - Percentage from top edge',
                'name' => 'position_y',
                'type' => 'number',
                'column_width' => '',
                'default_value' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '%',
                'min' => '',
                'max' => '',
                'step' => '',
              ),
            ),
            'row_min' => 0,
            'row_limit' => '',
            'layout' => 'table',
            'button_label' => 'Add U-turn',
          ),
        ),
        'row_min' => 1,
        'row_limit' => '',
        'layout' => 'row',
        'button_label' => 'Add Route',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'map',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'no_box',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
}
