<?php

if(function_exists("register_field_group"))
{
  register_field_group(array (
    'id' => 'acf_records',
    'title' => 'Records',
    'fields' => array (
      array (
        'key' => 'field_524fc736b22b9',
        'label' => 'Course Records',
        'name' => '',
        'type' => 'tab',
      ),
      array (
        'key' => 'field_524fc788b22bb',
        'label' => 'Routes',
        'name' => 'course_record_routes',
        'type' => 'repeater',
        'sub_fields' => array (
          array (
            'key' => 'field_524fc79cb22bc',
            'label' => 'Route Name',
            'name' => 'name',
            'type' => 'text',
            'column_width' => '',
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'formatting' => 'html',
            'maxlength' => '',
          ),
          array (
            'key' => 'field_524fc7bbb22bd',
            'label' => 'Categories',
            'name' => 'events',
            'type' => 'repeater',
            'column_width' => '',
            'sub_fields' => array (
              array (
                'key' => 'field_524fc808b22be',
                'label' => 'Category Name',
                'name' => 'name',
                'type' => 'text',
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
              ),
              array (
                'key' => 'field_524fc81bb22bf',
                'label' => 'Winner',
                'name' => 'winner',
                'type' => 'text',
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
              ),
              array (
                'key' => 'field_524fc821b22c0',
                'label' => 'Time',
                'name' => 'time',
                'type' => 'text',
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
              ),
            ),
            'row_min' => 1,
            'row_limit' => '',
            'layout' => 'table',
            'button_label' => 'Add Category',
          ),
        ),
        'row_min' => 1,
        'row_limit' => '',
        'layout' => 'row',
        'button_label' => 'Add Route',
      ),
      array (
        'key' => 'field_524fef6711b57',
        'label' => 'Annual Records',
        'name' => '',
        'type' => 'tab',
      ),
      array (
        'key' => 'field_524ff00b11b58',
        'label' => 'Years',
        'name' => 'annual_record_years',
        'type' => 'repeater',
        'sub_fields' => array (
          array (
            'key' => 'field_524ff23411b59',
            'label' => 'Year',
            'name' => 'year',
            'type' => 'text',
            'column_width' => '',
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'formatting' => 'html',
            'maxlength' => '',
          ),
          array (
            'key' => 'field_524ff24711b5a',
            'label' => 'Routes',
            'name' => 'routes',
            'type' => 'repeater',
            'column_width' => '',
            'sub_fields' => array (
              array (
                'key' => 'field_524ff26111b5b',
                'label' => 'Route Name',
                'name' => 'name',
                'type' => 'text',
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
              ),
              array (
                'key' => 'field_524ff26711b5c',
                'label' => 'Categories',
                'name' => 'events',
                'type' => 'repeater',
                'column_width' => '',
                'sub_fields' => array (
                  array (
                    'key' => 'field_524ff27311b5d',
                    'label' => 'Category Name',
                    'name' => 'name',
                    'type' => 'text',
                    'column_width' => '',
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'html',
                    'maxlength' => '',
                  ),
                  array (
                    'key' => 'field_524ff3217189d',
                    'label' => 'Winners',
                    'name' => 'winners',
                    'type' => 'repeater',
                    'column_width' => '',
                    'sub_fields' => array (
                      array (
                        'key' => 'field_524ff3657189e',
                        'label' => 'Name',
                        'name' => 'name',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                      ),
                      array (
                        'key' => 'field_524ff3697189f',
                        'label' => 'Time',
                        'name' => 'time',
                        'type' => 'text',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                      ),
                    ),
                    'row_min' => 1,
                    'row_limit' => '',
                    'layout' => 'table',
                    'button_label' => 'Add Winner',
                  ),
                ),
                'row_min' => 1,
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Add Category',
              ),
            ),
            'row_min' => 1,
            'row_limit' => '',
            'layout' => 'row',
            'button_label' => 'Add Route',
          ),
        ),
        'row_min' => 1,
        'row_limit' => '',
        'layout' => 'row',
        'button_label' => 'Add Year',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'hall-of-fame-template.php',
          'order_no' => 1,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'no_box',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
}
